### PR TITLE
Fixes for puppet future parser/4 and darwin

### PR DESCRIPTION
**Pull request by edestecd**

### CODE REVIEW

**Comment by i11** [comment]
Hi,

Thanks! Could you please regress test it against puppet 3 if you haven't done it yet?

**Comment by edestecd** [comment]
How about a matrix in your Travis config that includes both versions of puppet, with and without  future parser.
Example: https://github.com/puppetlabs/puppetlabs-postgresql/blob/master/.travis.yml

**Comment by jlyheden** [comment]
@edestecd Good suggestion, added matrix to travis config, please rebase / pull in the latest changes from our master branch.

**Comment by edestecd** [comment]
I'll try and get that done later today.  There is a linting gem also that will yell at you if you make these mistakes.  I'll add that too.

**Comment by edestecd** [comment]
I will add this linting gem also, so we are reminded to not do this:
https://github.com/puppet-community/puppet-lint-unquoted_string-check

**Comment by edestecd** [comment]
@jlyheden All done!  Can you merge now please?

**Comment by jlyheden** [comment]
Merged, thanks!

**Pull request merged**
